Update dr2main.yml

diff --git a/.github/workflows/dr2main.yml b/.github/workflows/dr2main.yml
--- a/.github/workflows/dr2main.yml
+++ b/.github/workflows/dr2main.yml
@@ -1,15 +1,15 @@
 # This is a basic workflow to help you get started with Actions
 
-name: CI
+name: DR2Main
 
 # Controls when the workflow will run
 on:
   repository_dispatch:
     types: [trigger-my-workflow]
 #  push:
- #   branches: [ "dr2main" ]
-  #pull_request:
-#    branches: [ "dr2main" ]
+ #   branches: [ "main" ]
+ # pull_request:
+  #  branches: [ "main" ]
 #  schedule:
 #    - cron: "* */2 * * *" ##Running every 15min
 
@@ -17,21 +17,26 @@ permissions:
   id-token: write
   contents: write
   
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   # This workflow contains a single job called "build"
   build:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     environment: myenv
+    env:
+      USERNAME: ${{ secrets.MAINJF_USERNAME }}
+      API_KEY: ${{ secrets.MAINJF_API }}
+      DRUSERNAME: ${{ secrets.DRJF_USERNAME }}
+      DRAPI_KEY: ${{ secrets.DRJF_API }}
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          ref: 'refs/heads/main'
 
-      - name: read all the values from values.env and store it in Github env
+      - name: Read all the values from values.env and status.txt and store it in Github env variable
         run: |
           #Read from file status.txt
           while IFS='=' read -r key value; do
@@ -43,50 +48,126 @@ jobs:
           echo "$key=$value" >> $GITHUB_ENV
           done < values.env
           
-      - name: Ping check to artifactory
+      - name: Ping check to artifactory both main and dr
         run: |
+          ##Setting below to avoid failing complete pipeline
           set +e
           ###Ping check to SAAS_MAIN
-          USERNAME=${{ secrets.MAINJF_USERNAME }}
-          API_KEY=${{ secrets.MAINJF_API }}
-          ARTIFACTORY_URL=${{ vars.MAINJF_URL }}
-          #ARTIFACTORY_URL=$MAINJF_URL
+          ARTIFACTORY_URL=${{ env.MAINJF_URL }}
           response=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$API_KEY" "${ARTIFACTORY_URL}artifactory/api/system/ping")
           [ "$response" -eq 200 ] && echo "main_status=success" >> $GITHUB_ENV || echo "main_status=fail" >> $GITHUB_ENV
           
           ###Ping check to SAAS_DR
-          #DRUSERNAME=${{ secrets.DRJF_USERNAME }}
-          #DRAPI_KEY=${{ secrets.DRJF_API }}
-          #DRARTIFACTORY_URL=${{ vars.DRF_URL }}
-          #responsedr=$(curl -s -o /dev/null -w "%{http_code}" -u "$DRUSERNAME:$DRAPI_KEY" "${DRARTIFACTORY_URL}artifactory/api/system/ping")
-          #[ "$responsedr" -eq 200 ] && dr_status=success || dr_status=fail
+          DRARTIFACTORY_URL=${{ env.DRJF_URL }}
+          responsedr=$(curl -s -o /dev/null -w "%{http_code}" -u "$DRUSERNAME:$DRAPI_KEY" "${DRARTIFACTORY_URL}artifactory/api/system/ping")
+          [ "$responsedr" -eq 200 ] && dr_status=success || dr_status=fail
+ 
+      - name: Fail workflow if SAAS main is down
+        run: |
+          if [ "$main_status" == "fail" ];then
+            echo "SAAS Main is down. Exiting"
+            exit 1
+          fi
+        
+      - name: Setup JFrog CLI for SAAS main
+        uses: jfrog/setup-jfrog-cli@v4
+        env:  
+          JF_URL: ${{ env.MAINJF_URL }}
+        with:
+          oidc-provider-name: sumgithub
+          custom-server-id: ${{ env.jpdMain }}
+          version: ${{ env.JFCliVersion }}
 
+      -  name: Setup JFrog CLI SAAS DR
+         uses: jfrog/setup-jfrog-cli@v4
+         env:  
+           JF_URL: ${{ env.DRJF_URL }}
+         with:
+           oidc-provider-name: destgithub
+           custom-server-id: ${{ env.jpdDr }}
+           version: ${{ env.JFCliVersion }}
+
+      - name: print configured JFrog CLIs details
+        run: |
+          jf c s
           
-      - name: Check conditions before proceeding
+      - name: Download and install plugin proj-sync and repo-sync from DR artifactory
         run: |
           set +e
-          requestDateTime=$requestDateTime
-          echo "requestDateTime $requestDateTime"
-          if [ $requestDateTime == "" ]; then 
-            echo "[WARN] requestDateTime properties could NOT be found . Check if the Health Check pipeline has run on the DR side"
-            exit 1
-          fi
-          echo "canUpdateDR $canUpdateDR"
-          if [ $canUpdateDR == "" ];then
-            echo "[WARN] canUpdateDR properties could NOT be found . Check if the Health Check pipeline has run on the DR side"
-            exit 1
-          fi
-          epochNow=$(date +%s)
-          interval=$(expr $epochNow - $requestDateTime)
-          echo $epochNow
-          echo $requestDateTime
-          echo $interval
-          if [ $interval -gt $HealthCheckIntervalInSec ] ; then 
-            echo "[ERROR] the last update on the  statusFile  was more than $HealthCheckIntervalInSec seconds."
-            exit 1
-          fi
-          if [[ $canUpdateDR == "false" ]] ; then
-            echo "[WARN] File status.txt has : canUpdateDR=false; No sync will be pushed to the DR."
-            #curl -XPOST -H "authorization: jfrogPassword_011" https://psemea-pipelines-api.jfrog.io/v1/projectIntegrations/29/hook
-            exit 2
-          fi
+          export JFROG_CLI_PLUGINS_SERVER=$jpdDr
+          export JFROG_CLI_PLUGINS_REPO=$automationRepo
+          export JFROG_CLI_LOG_LEVEL=DEBUG
+          sleep 1
+          jf plugin install $cliPluginName@$cliPluginVersion
+          sleep 1
+          jf plugin install $projectPluginName@$projectPluginVersion
+          
+           
+
+#      - name: CreateUpdateProjects
+#        run: |
+#          export JFROG_CLI_LOG_LEVEL=DEBUG
+#          ~/.jfrog/plugins/proj-sync/bin/${projectPluginName} diff create $jpdMain $jpdDr
+
+      - name: createLocalRepositories
+        run: |
+          for projName in $(curl -XGET -H "Authorization: Bearer ${DRAPI_KEY}" "${DRJF_URL}access/api/v1/projects" -s | jq -r '.[].project_key')
+          do
+            jf $cliPluginName create local $jpdDr $jpdMain --project-key=$projName --dry-run=false --inventory=false
+          done
+          jf $cliPluginName create local $jpdDr $jpdMain  --dry-run=false --inventory=false
+
+      - name: createRemoteRepositories
+        run: |
+          for projName in $(curl -XGET -H "Authorization: Bearer ${DRAPI_KEY}" "${DRJF_URL}access/api/v1/projects" -s | jq -r '.[].project_key')
+          do
+                jf $cliPluginName create remote $jpdDr $jpdMain --project-key=$projName --dry-run=false --inventory=false
+          done
+          jf $cliPluginName create remote $jpdDr $jpdMain  --dry-run=false --inventory=false
+
+      - name: createVirtualRepositories
+        run: |
+          for projName in $(curl -XGET -H "Authorization: Bearer ${DRAPI_KEY}" "${DRJF_URL}access/api/v1/projects" -s | jq -r '.[].project_key')
+          do
+            jf $cliPluginName create virtual $jpdDr $jpdMain --project-key=$projName --dry-run=false --inventory=false
+          done
+          jf $cliPluginName create virtual $jpdDr $jpdMain  --dry-run=false --inventory=false
+
+      - name: UpdateLocalRepositories
+        run: |
+          i=0
+          N=50
+          for projName in $(curl -XGET -H "Authorization: Bearer ${DRAPI_KEY}" "${DRJF_URL}access/api/v1/projects" -s | jq -r '.[].project_key')
+          do
+                jf $cliPluginName update local $jpdDr $jpdMain --project-key=$projName --dry-run=false &
+                i=`expr $i + 1`
+                if [[ `expr $i % $N` == 0 ]]; then
+                        wait
+                fi
+          done
+          
+      - name: UpdateRemoteRepositories
+        run: |
+          i=0
+          N=50
+          for projName in $(curl -XGET -H "Authorization: Bearer ${DRAPI_KEY}" "${DRJF_URL}access/api/v1/projects" -s | jq -r '.[].project_key')
+          do
+                jf $cliPluginName update remote $jpdDr $jpdMain --project-key=$projName --dry-run=false &
+                i=`expr $i + 1`
+                if [[ `expr $i % $N` == 0 ]]; then
+                        wait
+                fi
+          done
+
+      - name: UpdateVirtualRepositories
+        run: |
+          i=0
+          N=50
+          for projName in $(curl -XGET -H "Authorization: Bearer ${DRAPI_KEY}" "${DRJF_URL}access/api/v1/projects" -s | jq -r '.[].project_key')
+          do
+                jf $cliPluginName update virtual $jpdDr $jpdMain --project-key=$projName --dry-run=false &
+                i=`expr $i + 1`
+                if [[ `expr $i % $N` == 0 ]]; then
+                        wait
+                fi
+          done
