Update healthcheck.yml

diff --git a/.github/workflows/healthcheck.yml b/.github/workflows/healthcheck.yml
--- a/.github/workflows/healthcheck.yml
+++ b/.github/workflows/healthcheck.yml
@@ -57,14 +57,14 @@ jobs:
           ARTIFACTORY_URL=${{ vars.MAINJF_URL }}
           #ARTIFACTORY_URL=$MAINJF_URL
           response=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$API_KEY" "${ARTIFACTORY_URL}artifactory/api/system/ping")
-          [ "$response" -eq 200 ] && echo "main_status=success" >> $GITHUB_ENV || echo "main_status=fail" >> $GITHUB_ENV
+          [ $response -eq 200 ] && echo "main_status=success" >> $GITHUB_ENV || echo "main_status=fail" >> $GITHUB_ENV
           
           ###Ping check to SAAS_DR
           DRUSERNAME=${{ secrets.DRJF_USERNAME }}
           DRAPI_KEY=${{ secrets.DRJF_API }}
-          DRARTIFACTORY_URL=${{ vars.DRF_URL }}
+          DRARTIFACTORY_URL=${{ vars.DRJF_URL }}
           responsedr=$(curl -s -o /dev/null -w "%{http_code}" -u "$DRUSERNAME:$DRAPI_KEY" "${DRARTIFACTORY_URL}artifactory/api/system/ping")
-          [ "$responsedr" -eq 200 ] && dr_status=success || dr_status=fail
+          [ $responsedr -eq 200 ] && echo "dr_status=success" >> $GITHUB_ENV || echo "dr_status=fail" >> $GITHUB_ENV
           echo "responsedr $responsedr"
           echo "response $response"
 
