Update reposync.yml

diff --git a/.github/workflows/reposync.yml b/.github/workflows/reposync.yml
--- a/.github/workflows/reposync.yml
+++ b/.github/workflows/reposync.yml
@@ -41,11 +41,6 @@ jobs:
           while IFS='=' read -r key value; do
           echo "$key=$value" >> $GITHUB_ENV
           done < values.env
-
-
-      - name: print values
-        run: |
-          echo "lastHeartBeatFromMain $lastHeartBeatFromMain"
           
       - name: Ping check to artifactory
         run: |
@@ -68,8 +63,28 @@ jobs:
           
       - name: Check conditions before proceeding
         run: |
-          requestDateTimenew=$requestDateTime
+          set +e
+          requestDateTime=$requestDateTime
           echo "requestDateTime $requestDateTime"
+          if [ $requestDateTime -eq "" ]; then 
+            echo "[WARN] requestDateTime properties could NOT be found . Check if the Health Check pipeline has run on the DR side"
+            exit 1
+          fi
+          echo "canUpdateDR $canUpdateDR"
+          if [ $canUpdateDR == "" ];then
+            echo "[WARN] canUpdateDR properties could NOT be found . Check if the Health Check pipeline has run on the DR side"
+            exit 1
+          fi
+          epochNow=$(date +%s)
+          interval=$(expr $epochNow - $requestDateTime)
+          echo $epochNow
+          echo $requestDateTime
+          echo $interval
+          
+        
+          
+          
+          
 
 
            
