Update reposync.yml

diff --git a/.github/workflows/reposync.yml b/.github/workflows/reposync.yml
--- a/.github/workflows/reposync.yml
+++ b/.github/workflows/reposync.yml
@@ -66,7 +66,7 @@ jobs:
           set +e
           requestDateTime=$requestDateTime
           echo "requestDateTime $requestDateTime"
-          if [ $requestDateTime -eq "" ]; then 
+          if [ $requestDateTime == "" ]; then 
             echo "[WARN] requestDateTime properties could NOT be found . Check if the Health Check pipeline has run on the DR side"
             exit 1
           fi
@@ -80,6 +80,15 @@ jobs:
           echo $epochNow
           echo $requestDateTime
           echo $interval
+          if [ $interval -gt $HealthCheckIntervalInSec ] ; then 
+            echo "[ERROR] the last update on the  statusFile  was more than $HealthCheckIntervalInSec seconds."
+            exit 1
+          fi
+          if [[ $canUpdateDR == "false" ]] ; then
+            echo "[WARN] File status.txt has : canUpdateDR=false; No sync will be pushed to the DR."
+            #curl -XPOST -H "authorization: jfrogPassword_011" https://psemea-pipelines-api.jfrog.io/v1/projectIntegrations/29/hook
+            exit 2
+          fi
           
         
           
